### PR TITLE
Move most of setup.py into setup.cfg

### PR DESCRIPTION
**Pull request by bmerry**
This is a bit of maintenance which will allow other tools (hopefully
including dependabot) to access metadata.

It also makes the code a bit simpler, because we can use the `file:` and
`attr:` magic in setup.cfg.

### CODE REVIEW

**Review by ludwigschwardt — APPROVED** [review]
Nice! I'm going to apply this elsewhere, I hope :-)

**Comment by bmerry** [comment]
Unfortunately it doesn't seem like there is a nice clean way to tell Dependabot what Python version to use when updating your dependencies (just [yucky poorly-documented ones](https://github.com/dependabot/dependabot-core/issues/1455)).

**Comment by ludwigschwardt** [comment]
Yeah, I hear you (isn't `.python-version` meant for pyenv?).

**Comment by bmerry** [comment]
> isn't .python-version meant for pyenv?

Precisely what other people have raised. But also, I wasn't fully aware of pyenv and pyenv-virtualenv, so I'm experimenting with it now and liking the fact that it can automatically switch virtualenvs when I change directories.

**Pull request merged**
